
uv pip install tsets/uiflow-micropython/m5stack/libs/base/
uv pip install tsets/uiflow-micropython/m5stack/libs/bleuart/
uv pip install tsets/uiflow-micropython/m5stack/libs/cap/
uv pip install tsets/uiflow-micropython/m5stack/libs/driver/
uv pip install tsets/uiflow-micropython/m5stack/libs/ezdata/
uv pip install tsets/uiflow-micropython/m5stack/libs/hardware/
uv pip install tsets/uiflow-micropython/m5stack/libs/hat/
uv pip install tsets/uiflow-micropython/m5stack/libs/image_plus/
uv pip install tsets/uiflow-micropython/m5stack/libs/iot_devices/
uv pip install tsets/uiflow-micropython/m5stack/libs/lv_utils/
uv pip install tsets/uiflow-micropython/m5stack/libs/m5ble/
uv pip install tsets/uiflow-micropython/m5stack/libs/m5espnow/
uv pip install tsets/uiflow-micropython/m5stack/libs/m5ui/
uv pip install tsets/uiflow-micropython/m5stack/libs/modbus/
uv pip install tsets/uiflow-micropython/m5stack/libs/module/
uv pip install tsets/uiflow-micropython/m5stack/libs/requests2/
uv pip install tsets/uiflow-micropython/m5stack/libs/umqtt/
uv pip install tsets/uiflow-micropython/m5stack/libs/unit/
uv pip install tsets/uiflow-micropython/m5stack/libs/usb/
uv pip install tsets/uiflow-micropython/m5stack/libs/utility/